name: Build

on:
- push

jobs:
  build-bepinex:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install .NET 5 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name: Fetch Until You Fall Bindings
        uses: actions/checkout@v2
        with:
          repository: nicoco007/UntilYouFallBindings
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          path: UntilYouFallBindings

      - name: Build
        run: dotnet build -c Release_BepInEx -p:GameDir=${{ github.workspace }}\UntilYouFallBindings AesKeyExtractorPlugin\AesKeyExtractorPlugin.csproj
        
      - name: Upload AesKeyExtractorPlugin
        uses: actions/upload-artifact@v2.2.4
        with:
          name: AesKeyExtractorPlugin-BepInEx
          path: AesKeyExtractorPlugin\bin\Release_BepInEx\net472\AesKeyExtractorPlugin.dll
  build-melonloader:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install .NET 5 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name: Fetch Until You Fall Bindings
        uses: actions/checkout@v2
        with:
          repository: nicoco007/UntilYouFallBindings
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          path: UntilYouFallBindings

      - name: Build
        run: dotnet build -c Release_MelonLoader -p:GameDir=${{ github.workspace }}\UntilYouFallBindings AesKeyExtractorPlugin\AesKeyExtractorPlugin.csproj
        
      - name: Upload AesKeyExtractorPlugin
        uses: actions/upload-artifact@v2.2.4
        with:
          name: AesKeyExtractorPlugin-MelonLoader
          path: AesKeyExtractorPlugin\bin\Release_MelonLoader\net472\AesKeyExtractorPlugin.dll
  build-app:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install .NET 5 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name: Build
        run: dotnet build -c Release SaveEditor\SaveEditor.csproj

      - name: Rename build folder
        working-directory: SaveEditor\bin\Release
        run: move net5.0-windows7.0 SaveEditor
        
      - name: Upload SaveEditor
        uses: actions/upload-artifact@v2.2.4
        with:
          name: SaveEditor
          path: SaveEditor\bin\Release
